name: pyoe_examples
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.10  # Stable Python version
  - numpy=1.22.*  # Ensure compatibility with other scientific libraries
  - scipy=1.11.4  # Scientific computing
  - pandas=2.2.3  # Data analysis
  - xarray=2024.10.0  # N-D labeled arrays
  - dask=2024.11.2  # Parallel computing
  - numba=0.60.0  # JIT compiler for Python
  - cython=3.0.11  # C extensions for Python
  - pip=24.3.1  # Python package installer
  - pip:
      - git+https://github.com/maahn/pamtra2.git  # Specific branch of pamtra2
      - git+https://github.com/maahn/pyOptimalEstimation.git  # Optimal estimation library
